var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/channels/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__05436z8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0hp4_yp.js")
R.c("server/chunks/ssr/[root-of-the-server]__00bfqp8._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0bd0tfh._.js")
R.c("server/chunks/ssr/src_0~zc6by._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_next-internal_server_app_channels_page_actions_05j8ajt.js")
R.m(74532)
module.exports=R.m(74532).exports
